name: Connectlife API proxy / MQTT Add-on
description: Integrates Connectlife AC devices with Home Assistant via MQTT and provides an HTTP API
version: 1.0.12
slug: connectlife-api-proxy-mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  connectlife_login: ""
  connectlife_password: ""
  temperature_unit: celsius
  log_level: info
  disable_http_api: true
  mqtt_host: ""
  mqtt_user: ""
  mqtt_password: ""
  mqtt_port: 1883
  mqtt_ssl: false
schema:
  connectlife_login: str
  connectlife_password: password
  temperature_unit: list(celsius|fahrenheit)
  log_level: list(emergency|alert|critical|error|warning|notice|info|debug)
  disable_http_api: bool
  mqtt_host: str?
  mqtt_user: str?
  mqtt_password: password?
  mqtt_port: int?
  mqtt_ssl: bool?
startup: services
init: false
services: ["mqtt:need"]
